const fs = require("fs");
const path = require("path");

const filePath = path.join(__dirname, "..", "mlbb-topup.html");
let html = fs.readFileSync(filePath, "utf8");

if (html.includes("id=\"authOverlay\"")) {
  console.log("Auth already injected. Nothing to do.");
  process.exit(0);
}

// 1. CSS
const css = [
".navbar{position:relative;z-index:10;display:flex;align-items:center;justify-content:space-between;padding:12px 28px;background:rgba(8,12,20,0.88);backdrop-filter:blur(12px);border-bottom:1px solid rgba(255,215,0,0.1);}",
".nav-logo{display:flex;align-items:center;gap:10px;text-decoration:none;}",
".nav-logo-icon{width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,#FFD700,#FF6B00);display:flex;align-items:center;justify-content:center;font-size:18px;}",
".nav-logo-text{font-family:'Orbitron',sans-serif;font-weight:700;font-size:1rem;background:linear-gradient(90deg,#FFD700,#FF6B00);-webkit-background-clip:text;-webkit-text-fill-color:transparent;}",
".nav-right{display:flex;align-items:center;gap:10px;}",
".nav-user{display:none;align-items:center;gap:10px;}",
".nav-user-name{font-family:'Rajdhani',sans-serif;font-weight:600;font-size:0.9rem;color:var(--gold);}",
".nav-avatar{width:34px;height:34px;border-radius:50%;background:linear-gradient(135deg,var(--gold),#FF6B00);display:flex;align-items:center;justify-content:center;font-weight:700;font-size:0.85rem;color:#000;}",
".btn-nav{padding:8px 20px;border-radius:50px;font-family:'Rajdhani',sans-serif;font-weight:700;font-size:0.88rem;cursor:pointer;transition:all 0.2s;border:none;}",
".btn-nav-login{background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.15);color:#fff;}",
".btn-nav-login:hover{background:rgba(255,255,255,0.12);border-color:rgba(255,215,0,0.4);color:var(--gold);}",
".btn-nav-register{background:linear-gradient(135deg,#FFD700,#FF6B00);color:#000;}",
".btn-nav-register:hover{transform:translateY(-1px);box-shadow:0 4px 20px rgba(255,215,0,0.4);}",
".btn-nav-logout{background:rgba(255,45,85,0.1);border:1px solid rgba(255,45,85,0.3);color:var(--red);padding:6px 16px;border-radius:50px;font-family:'Rajdhani',sans-serif;font-weight:600;font-size:0.82rem;cursor:pointer;}",
".btn-nav-logout:hover{background:rgba(255,45,85,0.2);}",
".auth-overlay{position:fixed;inset:0;background:rgba(0,0,0,0.78);z-index:500;display:none;align-items:center;justify-content:center;backdrop-filter:blur(6px);}",
".auth-overlay.open{display:flex;}",
".auth-box{background:#0E1422;border:1px solid rgba(255,215,0,0.15);border-radius:20px;padding:36px 32px;width:100%;max-width:440px;position:relative;max-height:90vh;overflow-y:auto;}",
".auth-box::-webkit-scrollbar{width:4px;}",
".auth-box::-webkit-scrollbar-thumb{background:rgba(255,215,0,0.3);border-radius:4px;}",
".auth-box::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,transparent,#FFD700,transparent);border-radius:20px 20px 0 0;}",
".auth-close{position:absolute;top:14px;right:16px;background:none;border:none;color:var(--text-muted);font-size:1.4rem;cursor:pointer;line-height:1;}",
".auth-close:hover{color:#fff;}",
".auth-title{font-family:'Orbitron',sans-serif;font-size:1.3rem;font-weight:700;color:#fff;margin-bottom:6px;}",
".auth-sub{font-size:0.82rem;color:var(--text-muted);margin-bottom:22px;line-height:1.5;}",
".auth-field{margin-bottom:14px;}",
".auth-field label{display:block;font-family:'Rajdhani',sans-serif;font-size:0.75rem;font-weight:600;letter-spacing:1.5px;text-transform:uppercase;color:var(--text-muted);margin-bottom:6px;}",
".auth-field input,.auth-field select{width:100%;background:rgba(255,255,255,0.05);border:1px solid rgba(255,215,0,0.15);border-radius:10px;padding:12px 14px;font-family:'Exo 2',sans-serif;font-size:0.92rem;color:#fff;outline:none;transition:all 0.3s;}",
".auth-field input::placeholder{color:rgba(255,255,255,0.2);}",
".auth-field input:focus,.auth-field select:focus{border-color:var(--gold);background:rgba(255,215,0,0.04);box-shadow:0 0 16px rgba(255,215,0,0.08);}",
".auth-field select{appearance:none;cursor:pointer;background-color:#0E1422;}",
".auth-phone-row{display:grid;grid-template-columns:160px 1fr;gap:10px;}",
".auth-pw-wrap{position:relative;}",
".auth-pw-wrap input{padding-right:44px;}",
".auth-pw-toggle{position:absolute;right:12px;top:50%;transform:translateY(-50%);background:none;border:none;color:var(--text-muted);cursor:pointer;font-size:0.85rem;padding:4px;}",
".auth-pw-toggle:hover{color:var(--gold);}",
".auth-name-row{display:grid;grid-template-columns:1fr 1fr;gap:12px;}",
".auth-check-row{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px;}",
".auth-remember{display:flex;align-items:center;gap:8px;font-size:0.82rem;color:var(--text-muted);cursor:pointer;}",
".auth-remember input[type=checkbox]{accent-color:var(--gold);width:14px;height:14px;}",
".auth-forgot{font-size:0.82rem;color:var(--gold);text-decoration:none;font-family:'Rajdhani',sans-serif;font-weight:600;}",
".auth-forgot:hover{text-decoration:underline;}",
".auth-submit{width:100%;background:linear-gradient(135deg,#FFD700,#FF6B00);border:none;border-radius:50px;padding:13px;font-family:'Orbitron',sans-serif;font-weight:700;font-size:0.85rem;color:#000;cursor:pointer;letter-spacing:1px;transition:all 0.3s;margin-bottom:14px;}",
".auth-submit:hover{transform:translateY(-2px);box-shadow:0 6px 28px rgba(255,215,0,0.45);}",
".auth-submit:disabled{opacity:0.5;cursor:not-allowed;transform:none;}",
".auth-switch{text-align:center;font-size:0.82rem;color:var(--text-muted);margin-bottom:8px;}",
".auth-switch-btn{width:100%;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:50px;padding:11px;font-family:'Rajdhani',sans-serif;font-weight:700;font-size:0.88rem;color:#ccc;cursor:pointer;transition:all 0.2s;display:flex;align-items:center;justify-content:center;gap:8px;}",
".auth-switch-btn:hover{background:rgba(255,255,255,0.1);color:#fff;}",
".auth-err{font-size:0.8rem;color:var(--red);min-height:16px;margin-bottom:6px;text-align:center;}",
".auth-ok{font-size:0.8rem;color:#00E676;min-height:16px;margin-bottom:6px;text-align:center;}",
".login-gate{display:none;margin-top:16px;padding:18px 22px;background:rgba(255,215,0,0.06);border:1px solid rgba(255,215,0,0.2);border-radius:14px;text-align:center;}",
".login-gate p{font-family:'Rajdhani',sans-serif;font-size:0.95rem;color:var(--text-muted);margin-bottom:12px;}",
".login-gate p strong{color:var(--gold);}",
".gate-btns{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;}",
".gate-btn-login{padding:10px 28px;background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.2);border-radius:50px;color:#fff;font-family:'Rajdhani',sans-serif;font-weight:700;font-size:0.88rem;cursor:pointer;transition:all 0.2s;}",
".gate-btn-login:hover{border-color:var(--gold);color:var(--gold);}",
".gate-btn-register{padding:10px 28px;background:linear-gradient(135deg,#FFD700,#FF6B00);border:none;border-radius:50px;color:#000;font-family:'Rajdhani',sans-serif;font-weight:700;font-size:0.88rem;cursor:pointer;transition:all 0.2s;}",
".gate-btn-register:hover{transform:translateY(-1px);box-shadow:0 4px 20px rgba(255,215,0,0.4);}"
].join("\n");
html = html.replace("</style>", css + "\n</style>");

// 2. Navbar + Modal
const nav = [
'<nav class="navbar">',
'  <a class="nav-logo" href="#">',
'    <div class="nav-logo-icon">&#x1F48E;</div>',
'    <span class="nav-logo-text">MLBB TOP UP</span>',
'  </a>',
'  <div class="nav-right">',
'    <div class="nav-user" id="navUser">',
'      <div class="nav-avatar" id="navAvatar">A</div>',
'      <span class="nav-user-name" id="navUserName">User</span>',
'      <button class="btn-nav-logout" id="navLogoutBtn">Logout</button>',
'    </div>',
'    <div id="navAuthBtns">',
'      <button class="btn-nav btn-nav-login" id="navLoginBtn">Login</button>',
'      <button class="btn-nav btn-nav-register" id="navRegisterBtn">Register</button>',
'    </div>',
'  </div>',
'</nav>',
'<div class="auth-overlay" id="authOverlay">',
'  <div class="auth-box">',
'    <button class="auth-close" id="authClose">&#x00D7;</button>',
'    <div id="panelLogin">',
'      <div class="auth-title">Sign In</div>',
'      <div class="auth-sub">Please sign in to your account and start the adventure...</div>',
'      <div class="auth-field"><label>Your Email or Username or Phone Number</label><input type="text" id="loginIdentifier" placeholder="name@example.com" /></div>',
'      <div class="auth-field"><label>Your password</label><div class="auth-pw-wrap"><input type="password" id="loginPassword" placeholder="Password" /><button class="auth-pw-toggle" id="toggleLoginPw">&#x1F441;</button></div></div>',
'      <div class="auth-check-row">',
'        <label class="auth-remember"><input type="checkbox" id="rememberMe" /> Remember me</label>',
'        <a href="#" class="auth-forgot">Forgot Password</a>',
'      </div>',
'      <div class="auth-err" id="loginErr"></div>',
'      <button class="auth-submit" id="loginSubmit">Sign In</button>',
'      <div class="auth-switch">Don\'t have any account?</div>',
'      <button class="auth-switch-btn" id="goRegister">Register</button>',
'    </div>',
'    <div id="panelRegister" style="display:none;">',
'      <div class="auth-title">Sign Up</div>',
'      <div class="auth-sub">Create your MLBB TopUp Nepal account</div>',
'      <div class="auth-name-row">',
'        <div class="auth-field"><label>First name</label><input type="text" id="regFirst" placeholder="John" /></div>',
'        <div class="auth-field"><label>Last name</label><input type="text" id="regLast" placeholder="Doe" /></div>',
'      </div>',
'      <div class="auth-field"><label>Username</label><input type="text" id="regUsername" placeholder="username" /></div>',
'      <div class="auth-field"><label>Your Email</label><input type="email" id="regEmail" placeholder="email@example.com" /></div>',
'      <div class="auth-field">',
'        <label>Your Phone Number</label>',
'        <div class="auth-phone-row">',
'          <select id="regCountry"><option value="+977">Nepal (+977)</option><option value="+91">India (+91)</option><option value="+1">USA (+1)</option><option value="+44">UK (+44)</option><option value="+61">Australia (+61)</option><option value="+65">Singapore (+65)</option></select>',
'          <input type="tel" id="regPhone" placeholder="Your Phone Number" />',
'        </div>',
'      </div>',
'      <div class="auth-field"><label>Your password</label><div class="auth-pw-wrap"><input type="password" id="regPassword" placeholder="Password" /><button class="auth-pw-toggle" id="toggleRegPw">&#x1F441;</button></div></div>',
'      <div class="auth-field"><label>Confirm password</label><div class="auth-pw-wrap"><input type="password" id="regConfirm" placeholder="Confirm Password" /><button class="auth-pw-toggle" id="toggleRegConfirm">&#x1F441;</button></div></div>',
'      <div class="auth-err" id="registerErr"></div>',
'      <div class="auth-ok" id="registerOk"></div>',
'      <button class="auth-submit" id="registerSubmit">Register</button>',
'      <div class="auth-switch">Already an user?</div>',
'      <button class="auth-switch-btn" id="goLogin">Sign in</button>',
'    </div>',
'  </div>',
'</div>'
].join("\n");

html = html.replace('<div class="particles" id="particles"></div>', nav + '\n<div class="particles" id="particles"></div>');

// 3. Purchase gate
const gate = [
'    <div class="login-gate" id="loginGate">',
'      <p><strong>Login required</strong> to complete your purchase</p>',
'      <div class="gate-btns">',
'        <button class="gate-btn-login" id="gateLoginBtn">Sign In</button>',
'        <button class="gate-btn-register" id="gateRegisterBtn">Create Account</button>',
'      </div>',
'    </div>'
].join("\n");
html = html.replace(
  '<button class="order-btn" id="orderBtn">&#x26A1; PLACE ORDER NOW</button>',
  '<button class="order-btn" id="orderBtn">&#x26A1; PLACE ORDER NOW</button>\n' + gate
);

// 4. Auth JS
const authJS = [
'var currentUser = null;',
'try { var _su = localStorage.getItem("mlbb_user"); if (_su) currentUser = JSON.parse(_su); } catch(e) {}',
'',
'function updateNavUI() {',
'  if (currentUser) {',
'    document.getElementById("navUser").style.display = "flex";',
'    document.getElementById("navAuthBtns").style.display = "none";',
'    document.getElementById("navUserName").textContent = currentUser.name || currentUser.email.split("@")[0];',
'    document.getElementById("navAvatar").textContent = (currentUser.name || currentUser.email)[0].toUpperCase();',
'    var g = document.getElementById("loginGate"); if(g) g.style.display = "none";',
'  } else {',
'    document.getElementById("navUser").style.display = "none";',
'    document.getElementById("navAuthBtns").style.display = "flex";',
'  }',
'}',
'',
'function showAuth(panel) {',
'  document.getElementById("authOverlay").classList.add("open");',
'  document.getElementById("panelLogin").style.display    = panel === "login"    ? "block" : "none";',
'  document.getElementById("panelRegister").style.display = panel === "register" ? "block" : "none";',
'  document.getElementById("loginErr").textContent = "";',
'  document.getElementById("registerErr").textContent = "";',
'  document.getElementById("registerOk").textContent = "";',
'}',
'function closeAuth() { document.getElementById("authOverlay").classList.remove("open"); }',
'',
'function setupPwToggle(btnId, inputId) {',
'  document.getElementById(btnId).addEventListener("click", function() {',
'    var inp = document.getElementById(inputId);',
'    inp.type = inp.type === "password" ? "text" : "password";',
'    this.style.opacity = inp.type === "text" ? "1" : "0.5";',
'  });',
'}',
'setupPwToggle("toggleLoginPw", "loginPassword");',
'setupPwToggle("toggleRegPw", "regPassword");',
'setupPwToggle("toggleRegConfirm", "regConfirm");',
'',
'document.getElementById("navLoginBtn").addEventListener("click",     function(){ showAuth("login"); });',
'document.getElementById("navRegisterBtn").addEventListener("click",  function(){ showAuth("register"); });',
'document.getElementById("authClose").addEventListener("click",       closeAuth);',
'document.getElementById("authOverlay").addEventListener("click",     function(e){ if(e.target===this) closeAuth(); });',
'document.getElementById("goRegister").addEventListener("click",      function(){ showAuth("register"); });',
'document.getElementById("goLogin").addEventListener("click",         function(){ showAuth("login"); });',
'document.getElementById("gateLoginBtn").addEventListener("click",    function(){ showAuth("login"); });',
'document.getElementById("gateRegisterBtn").addEventListener("click", function(){ showAuth("register"); });',
'document.getElementById("navLogoutBtn").addEventListener("click", function() {',
'  currentUser = null;',
'  localStorage.removeItem("mlbb_user");',
'  localStorage.removeItem("mlbb_token");',
'  updateNavUI();',
'  showToast("Logged out successfully");',
'});',
'',
'document.getElementById("loginSubmit").addEventListener("click", function() {',
'  var id  = document.getElementById("loginIdentifier").value.trim();',
'  var pw  = document.getElementById("loginPassword").value;',
'  var err = document.getElementById("loginErr");',
'  err.textContent = "";',
'  if (!id || !pw) { err.textContent = "Please fill in all fields"; return; }',
'  var btn = this; btn.disabled = true; btn.textContent = "Signing in...";',
'  fetch(API + "/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: id, password: pw }) })',
'  .then(function(r){ return r.json().then(function(d){ return {ok:r.ok,d:d}; }); })',
'  .then(function(res){',
'    btn.disabled = false; btn.textContent = "Sign In";',
'    if (!res.ok) { err.textContent = res.d.error || "Login failed"; return; }',
'    currentUser = res.d.user;',
'    localStorage.setItem("mlbb_user", JSON.stringify(res.d.user));',
'    localStorage.setItem("mlbb_token", res.d.token);',
'    closeAuth(); updateNavUI();',
'    showToast("Welcome back, " + (res.d.user.name || res.d.user.email.split("@")[0]) + "!");',
'  })',
'  .catch(function(){ btn.disabled=false; btn.textContent="Sign In"; err.textContent="Cannot reach server"; });',
'});',
'',
'document.getElementById("registerSubmit").addEventListener("click", function() {',
'  var first   = document.getElementById("regFirst").value.trim();',
'  var last    = document.getElementById("regLast").value.trim();',
'  var uname   = document.getElementById("regUsername").value.trim();',
'  var email   = document.getElementById("regEmail").value.trim();',
'  var country = document.getElementById("regCountry").value;',
'  var phone   = document.getElementById("regPhone").value.trim();',
'  var pw      = document.getElementById("regPassword").value;',
'  var confirm = document.getElementById("regConfirm").value;',
'  var err = document.getElementById("registerErr");',
'  var ok  = document.getElementById("registerOk");',
'  err.textContent = ""; ok.textContent = "";',
'  if (!first||!last||!uname||!email||!pw||!confirm) { err.textContent="Please fill in all required fields"; return; }',
'  if (pw !== confirm) { err.textContent="Passwords do not match"; return; }',
'  if (pw.length < 6) { err.textContent="Password must be at least 6 characters"; return; }',
'  var btn = this; btn.disabled = true; btn.textContent = "Creating account...";',
'  fetch(API + "/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: email, password: pw, name: first + " " + last }) })',
'  .then(function(r){ return r.json().then(function(d){ return {ok:r.ok,d:d}; }); })',
'  .then(function(res){',
'    btn.disabled = false; btn.textContent = "Register";',
'    if (!res.ok) { err.textContent = res.d.error || "Registration failed"; return; }',
'    currentUser = res.d.user;',
'    localStorage.setItem("mlbb_user", JSON.stringify(res.d.user));',
'    localStorage.setItem("mlbb_token", res.d.token);',
'    ok.textContent = "Account created! Welcome, " + first + "!";',
'    setTimeout(function(){ closeAuth(); updateNavUI(); showToast("Welcome, " + first + "!"); }, 900);',
'  })',
'  .catch(function(){ btn.disabled=false; btn.textContent="Register"; err.textContent="Cannot reach server"; });',
'});',
'',
'var _origPlaceOrder = placeOrder;',
'placeOrder = function() {',
'  if (!currentUser) {',
'    document.getElementById("loginGate").style.display = "block";',
'    document.getElementById("loginGate").scrollIntoView({ behavior: "smooth", block: "center" });',
'    return;',
'  }',
'  _origPlaceOrder();',
'};',
'',
'updateNavUI();'
].join("\n");

html = html.replace("loadPackages();\n</script>", "loadPackages();\n" + authJS + "\n</script>");

fs.writeFileSync(filePath, html, "utf8");
console.log("SUCCESS: mlbb-topup.html patched with login/register system.");
